# Generated by Django 5.2.8 on 2025-12-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOPE', '0002_article_liked_by_article_read_by_article_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If True, article can be viewed by unauthenticated users. If False, requires login.'),
        ),
    ]
